//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jysk2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnWidth
    {
        public int Id { get; set; }
        public int MM { get; set; }
        public int ColumnCount { get; set; }
    }
}
